# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g main_sopa.cc point_set.cc point_types.cc sub_tree.cc -o sopa

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f sopa