# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g main.cc point_set.cpp point_types.cpp sub_tree.cpp -o EMST

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f EMST
	rm -f emst_tree.dot
	rm -f emst_tree.pdf