# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g p07_main_grammar2CNF.cc p07_alfabeto.cc p07_terminales.cc p07_producciones.cc -o Grammar2CNF

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f Grammar2CNF