# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g p01_single_grades.cc p01_main_single_grades.cc -o p01_single_grades

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f p01_single_grades
	rm -rf p01_single_grades.dSYM