# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g p02_strings.cc p02_alfabeto.cc p02_main_strings.cc -o p02_strings

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f p02_strings
	rm -rf p02_strings.dSYM