# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g p06_main_NFA_to_DFA.cc p06_alfabeto.cc -o NFA2DFA

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f NFA2DFA