# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g p01_multiple_grades.cc p01_main_multiple_grades.cc -o p01_multiple_grades

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f p01_multiple_grades
	rm -rf p01_multiple_grades.dSYM