# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g p05_main_automata_simulator.cc p05_alfabeto.cc p05_estado.cc p05_automata.cc -o p05_automata_simulator

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f p05_automata_simulator
	rm -rf p05_automata_simulator.dSYM