# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g califications.cc main_califications.cc -o main_califications

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f main_califications
	rm -rf main_califications.dSYM