# Compilación
main:
	@echo "Compilando ficheros..."
	g++ -g main_TM_simulator.cc estados.cc -o TM_simulator

.PHONY: clean

# Eliminar archivos
clean:
	@echo "Eliminando ficheros compilados..."
	rm -f TM_simulator